Make datestemps in pointer filenames configurable
ACCESS-NRI/CICE pull request #9
Opened 2024-12-16 03:01 UTC by anton-seaice

This adds support in cice for the addition of datestamps to the pointer filenames to be configured through the nuopc option _restart_pointer_append_date_ .

2025-01-14 02:31 UTC, anton-seaice commented
Hi @chrisb13 and @aekiss 

This is needed to finalise the updated CICE version. So is a companion to https://github.com/COSIMA/access-om3/pull/250

2025-01-17 03:56 UTC, aekiss commented on cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
> +                                  restart_format, restart_chunksize , pointer_date
```suggestion
                                  restart_format, restart_chunksize, pointer_date
```

2025-01-17 03:58 UTC, aekiss commented on cicecore/shared/ice_restart_shared.F90
> +         pointer_date =  .false.   ! if true, append datestamp to pointer file
would this be less confusing, to match the default in `cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90`?
```suggestion
         pointer_date = .true.   ! if true, append datestamp to pointer file
```

2025-01-17 03:59 UTC, aekiss approved these changes
LGTM, just a couple of small suggestions

2025-01-17 04:05 UTC, anton-seaice commented on cicecore/shared/ice_restart_shared.F90
> +         pointer_date =  .false.   ! if true, append datestamp to pointer file
For whatever reason, I decided not the put this new variable within  ifdef #CESMCOUPLED. So in general, the default should be false, as the only use case where it should default to true is when #CESMCOUPLED is set.

However, we set #CESMCOUPLED to True but want this option set to false, leading to this PR

2025-01-24 00:55 UTC, dougiesquire requested changes
Thanks @anton-seaice. Currently, if a user sets `restart_pointer_append_date` without `CESMCOUPLED` it will have no effect. See my suggested change to fix this below.

2025-01-24 00:55 UTC, dougiesquire commented on cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
> +
```suggestion
#ifdef CESMCOUPLED
    pointer_date = .true.
#endif

    ! set CICE internal pointer_date variable based on nuopc settings
    ! this appends a datestamp to the "rpointer" file
    call NUOPC_CompAttributeGet(gcomp, name="restart_pointer_append_date", value=cvalue, isPresent=isPresent, isSet=isSet, rc=rc)
    if (ChkErr(rc,__LINE__,u_FILE_u)) return
    if (isPresent .and. isSet) pointer_date = (trim(cvalue) .eq. ".true.")
```

2025-01-24 02:31 UTC, anton-seaice commented on cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90
> +
Oh very neat

2025-01-24 02:47 UTC, dougiesquire approved these changes

2025-01-24 04:55 UTC, merged